spring.application.name=Restaurant API

usuario=Diogo
ambiente=dev

server.port=8081

# Datasource
spring.datasource.username=restaurant
spring.datasource.password=oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1522:xe
spriing.datasource.username=xxx
spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.default_schema=RESTAURANT

# HikariCP (Gerenciador de Conexões)
spring.datasource.hikari.maximumPoolSize=5

# Hibernate

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# Swagger
springdoc.swagger-ui.path=/


# Segurança
jwt.secret=Minh@Chav@
# Tempo de expiração do token em Mile segundos
jwt.expiration=86400000


# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
#logging.level.liquibase=DEBUG


