spring.application.name=Restaurant API

usuario=Diogo
ambiente=dev

server.port=8080

# Datasource
spring.datasource.url=xxx
spriing.datasource.username=xxx
spring.datasource.password=xxx
spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
spring.jpa.properties.hibernate.default_schema=VEM_SER
spring.datasource.hikari.maximumPoolSize=5

# Swagger
springdoc.swagger-ui.path=/

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Log de queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true